/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/flower_bouquet.glb 
Author: icecool (https://sketchfab.com/icecool)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flower-bouquet-48e92013548247a9ad486dc13110c9b4
Title: Flower Bouquet
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Flower(props) {
  const { nodes, materials } = useGLTF('/models/flower_bouquet.glb')
  return (
 
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.Leaves_001_Leaves1_0.geometry} material={materials.Leaves1} position={[0.099, 0.027, 0.308]} />
            <mesh geometry={nodes.Leaves_002_Leaves6_0.geometry} material={materials.Leaves6} position={[-0.115, 0.054, 0.267]} />
            <mesh geometry={nodes.Leaves_003_Leaves6_0.geometry} material={materials.Leaves6} position={[0.036, -0.122, 0.298]} />
            <mesh geometry={nodes.Ribbons_001_Ribbons1_0.geometry} material={materials.Ribbons1} position={[0.008, 0.004, 0.147]} />
            <mesh geometry={nodes.Ribbons_002_Ribbons1_0.geometry} material={materials.Ribbons1} position={[0.006, 0.005, 0.142]} />
            <mesh geometry={nodes.Ribbons_003_Ribbons1_0.geometry} material={materials.Ribbons1} position={[0.008, -0.03, 0.145]} />
            <mesh geometry={nodes.Ribbons_004_Ribbons1_0.geometry} material={materials.Ribbons1} position={[-0.015, -0.045, 0.131]} />
            <mesh geometry={nodes.Ribbons_005_Ribbons1_0.geometry} material={materials.Ribbons1} position={[-0.001, -0.039, 0.144]} />
            <mesh geometry={nodes.Ribbons_006_Ribbons1_0.geometry} material={materials.Ribbons1} position={[0.002, -0.033, 0.141]} />
            <mesh geometry={nodes.Ribbons_007_Ribbons1_0.geometry} material={materials.Ribbons1} position={[0.014, -0.024, 0.144]} />
            <mesh geometry={nodes.Petal_001_Petals1_0.geometry} material={materials.Petals1} position={[-0.097, 0.16, 0.421]} />
            <mesh geometry={nodes.Petal_002_Petals2_0.geometry} material={materials.Petals2} position={[-0.147, 0.071, 0.464]} />
            <mesh geometry={nodes.Petal_003_Petals3_0.geometry} material={materials.Petals3} position={[-0.055, 0.172, 0.347]} />
            <mesh geometry={nodes.Petal_004_Petals4_0.geometry} material={materials.Petals4} position={[-0.169, -0.139, 0.381]} />
            <mesh geometry={nodes.Petal_005_Petals5_0.geometry} material={materials.Petals5} position={[-0.064, -0.149, 0.441]} />
            <mesh geometry={nodes.Petal_006_Petals6_0.geometry} material={materials.Petals6} position={[-0.088, -0.014, 0.439]} />
            <mesh geometry={nodes.Petal_007_Petals7_0.geometry} material={materials.Petals7} position={[0.036, 0.086, 0.531]} />
            <mesh geometry={nodes.Petal_009_Petals8_0.geometry} material={materials.Petals8} position={[-0.162, 0.058, 0.361]} />
            <mesh geometry={nodes.Petal_008_Petals9_0.geometry} material={materials.Petals9} position={[0.076, -0.17, 0.445]} />
            <mesh geometry={nodes.Petal_010_Petals10_0.geometry} material={materials.Petals10} position={[-0.193, 0.014, 0.4]} />
            <mesh geometry={nodes.Petal_011_Petals11_0.geometry} material={materials.Petals11} position={[-0.016, -0.077, 0.464]} />
            <mesh geometry={nodes.Petal_012_Petals12_0.geometry} material={materials.Petals12} position={[-0.122, -0.075, 0.461]} />
            <mesh geometry={nodes.Petal_013_Petals14_0.geometry} material={materials.Petals14} position={[-0.026, 0.117, 0.433]} />
            <mesh geometry={nodes.Petal_014_Petals1_0.geometry} material={materials.Petals1} position={[0.069, 0.157, 0.453]} />
            <mesh geometry={nodes.Petal_015_Petals2_0.geometry} material={materials.Petals2} position={[0.118, 0.073, 0.483]} />
            <mesh geometry={nodes.Petal_016_Petals3_0.geometry} material={materials.Petals3} position={[0.047, 0.196, 0.349]} />
            <mesh geometry={nodes.Petal_017_Petals6_0.geometry} material={materials.Petals6} position={[0.185, -0.015, 0.432]} />
            <mesh geometry={nodes.Petal_018_Petals7_0.geometry} material={materials.Petals7} position={[0.211, 0.053, 0.37]} />
            <mesh geometry={nodes.Petal_019_Petals8_0.geometry} material={materials.Petals8} position={[-0.052, 0.082, 0.516]} />
            <mesh geometry={nodes.Petal_020_Petals10_0.geometry} material={materials.Petals10} position={[0.109, -0.025, 0.51]} />
            <mesh geometry={nodes.Petal_021_Petals14_0.geometry} material={materials.Petals14} position={[0.172, -0.106, 0.372]} />
            <mesh geometry={nodes.Petal_022_Petals2_0.geometry} material={materials.Petals2} position={[-0.019, -0.183, 0.354]} />
            <mesh geometry={nodes.Petal_023_Petals8_0.geometry} material={materials.Petals8} position={[0.041, -0.131, 0.405]} />
            <mesh geometry={nodes.Petal_024_Petals11_0.geometry} material={materials.Petals11} position={[0.09, -0.158, 0.366]} />
            <mesh geometry={nodes.Petal_025_Petals12_0.geometry} material={materials.Petals12} position={[-0.02, -0.107, 0.516]} />
            <mesh geometry={nodes.Petal_026_Petals11_0.geometry} material={materials.Petals11} position={[0.132, -0.072, 0.428]} />
            <mesh geometry={nodes.Petal_027_Petals8_0.geometry} material={materials.Petals8} position={[0.109, 0.088, 0.415]} />
            <mesh geometry={nodes.Stems_Stems_0.geometry} material={materials.Stems} position={[0.007, 0.001, 0.178]} />
            <mesh geometry={nodes.Petal_028_Petals11_0.geometry} material={materials.Petals11} position={[0.085, 0.076, 0.349]} />
            <mesh geometry={nodes.Petal_029_Petals11_0.geometry} material={materials.Petals11} position={[-0.158, -0.051, 0.388]} />
            <mesh geometry={nodes.Petal_030_Petals7_0.geometry} material={materials.Petals7} position={[-0.014, 0, 0.541]} />
            <mesh geometry={nodes.Petal_031_Petals11_0.geometry} material={materials.Petals11} position={[0.131, 0.133, 0.34]} />
            <mesh geometry={nodes.Petal_032_Petals11_0.geometry} material={materials.Petals11} position={[0.072, -0.098, 0.492]} />
            <mesh geometry={nodes.Petal_033_Petals12_0.geometry} material={materials.Petals12} position={[0.025, 0.008, 0.493]} />
            <mesh geometry={nodes.SmallPlants_001_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[-0.1, -0.092, 0.254]} />
            <mesh geometry={nodes.SmallPlants_002_SmallPlants1_0.geometry} material={materials.SmallPlants1} position={[-0.117, -0.119, 0.338]} />
            <mesh geometry={nodes.SmallPlants_003_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[0.06, 0.185, 0.317]} />
            <mesh geometry={nodes.SmallPlants_004_SmallPlants2_0.geometry} material={materials.SmallPlants2} position={[0.068, 0.197, 0.333]} />
            <mesh geometry={nodes.SmallPlants_005_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[0.166, 0.117, 0.307]} />
            <mesh geometry={nodes.SmallPlants_006_SmallPlants2_0.geometry} material={materials.SmallPlants2} position={[0.178, 0.122, 0.319]} />
            <mesh geometry={nodes.SmallPlants_007_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[0.168, -0.022, 0.316]} />
            <mesh geometry={nodes.SmallPlants_008_SmallPlants2_0.geometry} material={materials.SmallPlants2} position={[0.183, -0.025, 0.328]} />
            <mesh geometry={nodes.SmallPlants_009_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[0.064, -0.177, 0.341]} />
            <mesh geometry={nodes.SmallPlants_010_SmallPlants2_0.geometry} material={materials.SmallPlants2} position={[0.065, -0.188, 0.35]} />
            <mesh geometry={nodes.SmallPlants_011_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[-0.053, -0.146, 0.28]} />
            <mesh geometry={nodes.SmallPlants_012_SmallPlants2_0.geometry} material={materials.SmallPlants2} position={[-0.056, -0.157, 0.287]} />
            <mesh geometry={nodes.SmallPlants_013_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[-0.189, 0.028, 0.318]} />
            <mesh geometry={nodes.SmallPlants_014_SmallPlants2_0.geometry} material={materials.SmallPlants2} position={[-0.201, 0.028, 0.33]} />
            <mesh geometry={nodes.SmallPlants_015_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[-0.08, 0.065, 0.259]} />
            <mesh geometry={nodes.SmallPlants_016_SmallPlants1_0.geometry} material={materials.SmallPlants1} position={[-0.122, -0.088, 0.221]} />
            <mesh geometry={nodes.SmallPlants_017_SmallPlants3_0.geometry} material={materials.SmallPlants3} position={[-0.151, -0.035, 0.321]} />
            <mesh geometry={nodes.SmallPlants_018_SmallPlants2_0.geometry} material={materials.SmallPlants2} position={[-0.162, -0.037, 0.334]} />
            <mesh geometry={nodes.SmallPlants_019_SmallPlants1_0.geometry} material={materials.SmallPlants1} position={[0.142, -0.066, 0.283]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/flower_bouquet.glb')
