/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/old_wooden_door.glb 
Author: Ellie3D (https://sketchfab.com/Ellie3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/old-wooden-door-1cec090cd02142b094802d242e03ee7c
Title: Old wooden Door
*/
import { useState ,useEffect} from 'react'
import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import * as THREE from "three";
export function Gate(props) {

  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/old_wooden_door.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)


// useEffect(() => {
//   const action = actions["Door|DoorAction"];

//   if (!action) return;

//   // انقل الأنيميشن لآخر فريم (الباب مقفول)
//   action.time = action.getClip().duration;

//   // حدث الميكسر مرة واحدة لتطبيق الوضع
//   action.getMixer().update(0);

//   // أوقف الأنيميشن
//   action.paused = true;
// }, [actions]);

const openDoor = () => {
  const action = actions["Door|DoorAction"];
  if (!action) return;

  action.reset();
  action.setLoop(THREE.LoopOnce, 1);
  action.clampWhenFinished = true;

  action.timeScale = -1; // تشغيل بالعكس
  action.time = action.getClip().duration; // ابدأ من آخر فريم

  action.play();
};

  return (
    
    <group ref={group}  onClick={openDoor} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="DoorAnimatedfbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Door" position={[0, 0.895, -0.644]} rotation={[0, 0, -Math.PI]} scale={0.54}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_15" />
                    <group name="Object_17" />
                    <skinnedMesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials.Door} skeleton={nodes.Object_16.skeleton} />
                    <skinnedMesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials.Door} skeleton={nodes.Object_18.skeleton} />
                  </group>
                </group>
                <group name="Door_Right" />
                <group name="Door_left" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
    
  )

}

useGLTF.preload('/models/old_wooden_door.glb')
